name: Linter & tests checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🤖
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Run types check 🤔
        run: yarn run ts:check

      - name: Run linter 👀
        run: yarn run lint:errors
